dataset:
  input_path: inputs/fake_nutrition_nl.csv
  output_path: demo
columns:
  y_columns:
  - daily_kcal
  - protein_g
  - fruit_portions
  - gender
  id_columns:
  - gender
  - age
  - zip_code
  dp_columns:
  - age
  - zip_code
  drop_columns: []
  plot_column: daily_kcal
  zip_code_column: zip_code
synthesis:
  visit_sequence:
  - daily_kcal
  - protein_g
  - carbs_g
  - gender
  - fat_g
  - fruit_portions
  - zip_code
  - age
  methods:
    age: cart
    gender: polyreg
    zip_code: cart
    daily_kcal: cart
    protein_g: cart
    carbs_g: cart
    fat_g: cart
    fruit_portions: cart
  minnumlevels: 10
  maxfaclevels: 60
evaluation:
  epsilon: 0.8
  sensitivity: 1
  sample_per: 75
  memory: 400
environment:
  rscript_loc: /Library/Frameworks/R.framework/Resources/bin/Rscript
  synthpop_file: R_scripts/synthpop_script.R
