name: sdp
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10.18
  - pip=25.2
  - setuptools=78.1.1
  - wheel=0.45.1

  # Jupyter stack
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jupyter_core=5.8.1
  - jupyter_client=8.6.3
  - notebook=7.3.1
  - traitlets=5.14.3
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0

  # Core scientific stack
  - numpy=2.2.6
  - pandas=2.3.2
  - scipy=1.15.3
  - scikit-learn=1.7.2

  #  Visualization 
  - matplotlib=3.10.6
  - seaborn=0.11.2

  #  Geospatial stack 
  - shapely=2.1.1
  - geopandas=0.14.4
  - fiona=1.9.6

  #  Other dependencies 
  - psutil=7.0.0
  - python-dateutil=2.9.0.post0
  - packaging=25.0
  - joblib=1.5.2
  - pyarrow=17.0.0
  - rpy2=3.5.11   # requires R installed via Homebrew on macOS

  #  Pip-installed dependencies 
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.59.2
      - kiwisolver==1.4.9
      - kmodes==0.12.2
      - narwhals==2.4.0
      - pillow==11.3.0
      - pyparsing==3.2.3
      - pyreadstat==1.3.1
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.11.2
      - shapely==2.1.1
      - synthgauge==2.2.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
      - streamlit==1.56.0
      - streamlit-sortables==0.3.1
      - pyyaml==6.0.3
